### ISSUE TITLE
Firebase connection

### ISSUE THREAD

**Issue by AnthoniMarie** [Bartozzz/smog-alert-app#12]
Hello,

I just discovered your application which is really very interesting.
But the problem is, when I try to run it, I get this error: "FIREBASE FATAL ERROR: Can not parse Firebase url Please use https: // <YOURFIREBASE> .firebaseio.com".
I have however edited the .env with my information... 
could you help me?

Thank you so much !

**Comment by Bartozzz** [comment]
Salut Anthoni!

This app uses Firebase for storing all pins and polluter-related data. In order to run the app, you'll need to setup a Firebase Project yourself. Please, follow the instructions below:

1. Create a Firebase project in the [Firebase Console](https://console.firebase.google.com/).
2. From the project overview page in the Firebase console, click _"Add Firebase to your web app"_.
2. Rename `./.env.example` to `./.env` (should be at the root of the project).
3. Copy and paste your project's config to the `.env` file.

At the end, your `.env` file should look like this:

```
# Firebase config
API_KEY=<API_KEY>
AUTH_DOMAIN=<PROJECT_ID>.firebaseapp.com
DATABASE_URL=https://<DATABASE_NAME>.firebaseio.com
PROJECT_ID=<PROJECT_ID>
STORAGE_BUCKET=<BUCKET>.appspot.com
MESSAGING_SENDER_ID=<SENDER_ID>
```

**Comment by AnthoniMarie** [comment]
Merci pour cette réponse !

After having exactly filled everything as you indicated to me, I always have the same error that occurs ... However, I was careful to fill everything and especially be careful to rename the .env and make sure that it either at the root ...

What do you think of that?


Screenshot of my `.env` file:
https://pic.anthoni-marie.fr/y/2019/HxE-MyMUV.png

Screenshot of the app:
https://pic.anthoni-marie.fr/y/2019/kg6g7z87ee.png

Thank you :)

<blockquote></blockquote>
<blockquote></blockquote>

**Comment by Bartozzz** [comment]
Your `.env` file looks good. Make sure it is at the root of your project, i.e. in the same location as `package.json`.

I've just tried a fresh `$ git clone` and everything seems to work correctly on my device. My guess is that your machine ignores the `.env` file when building the app, and thus the Firebase config is wrong.

Try to put the following piece of code in `src/store/configureFirebase.js` at line 12 and check the output in your terminal when you launch the app:

```javascript
console.log({
  apiKey: API_KEY,
  authDomain: AUTH_DOMAIN,
  databaseURL: DATABASE_URL,
  projectId: PROJECT_ID,
  storageBucket: STORAGE_BUCKET,
  messagingSenderId: MESSAGING_SENDER_ID
});
```

If the logged object is empty, there might be something wrong with the installed dependencies, perhaps try to delete `./node_modules` and run `$ npm install` again.

**Comment by Bartozzz** [comment]
Forgot to mention – if you change/create a `.env` file, you'll need to restart the Expo server. Maybe running `$ npm start` (which is an alias for `$ expo start`) again will fix the issue. 😄

**Comment by AnthoniMarie** [comment]
Everything is working ! Thank you very much for your very clear explanations and a big congratulations for your application 😃

**Comment by Bartozzz** [comment]
Sure, glad it worked! There's still a lot of work to be done on this app – all pull requests are more than welcome. 😄
