### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by ssnjrthegr8** [Bartozzz/smog-alert-app#4]
Hi, can I contribute by designing a logo for your app?

**Comment by Bartozzz** [comment]
Sure, that would be awesome!

**Comment by ssnjrthegr8** [comment]
![g4978](https://user-images.githubusercontent.com/38104354/42732692-7365e5fe-8843-11e8-9a44-5c2079151455.png)


How does this look? The concept is I combined a geotag with an eye, which looks out for polluters, with an exclamation mark inside a smoky looking black cloud with a white outline behind it to indicate smog.


![gdg](https://user-images.githubusercontent.com/38104354/42732726-e0d92f10-8843-11e8-9dfe-cade552409da.png)

**Comment by Bartozzz** [comment]
It doesn't look bad but I would prefer that black cloud to be more circular so it could be used as an app icon. I think that the exclamation _point_ is a little bit unbalanced in terms of margin, perhaps you could move it a little bit up to make the bottom/top paddings consistent. Also, inner shadow would probably look better than the actual outer shadow in the eye (white point). But it looks good so far!

**Comment by Bartozzz** [comment]
Yep, the concept is perfect 👌

**Comment by Bartozzz** [comment]
I like it. Could you share some PSDs so I can adjust the size and play with it a little bit? Also, let me know if you want me to put any special contributions in the README 😄

**Comment by ssnjrthegr8** [comment]
I used Inkscape to make the logo and I don't use photoshop :( Would the vector file (.svg) be enough?

**Comment by Bartozzz** [comment]
Sure, no problem

**Comment by ssnjrthegr8** [comment]
Here are the files : https://drive.google.com/open?id=11YyJ_lAOnk545t-gOKHxvw0w-5OZiQkH sorry for the delay I had a lot of stuff to do :)

**Comment by Bartozzz** [comment]
Sure, no problem. Thanks a lot for your contribution!
